### ISSUE TITLE
Hot code reloading checklist

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#30]
Some example scenarios to check
- [x] After making a change, server-rendering works as expected (bug)
- [x] Errors render on the browser as well (with our existing style)
- [x] Works with path registration / unregistration.
  - [x] If I go to `/test` and `test.js` doesn't exist, render `404`. Creating it renders `test.js`
  - [x] If I create `test.js` but with an error, we replace the `404` with an error
  - [x] If `test.js` has an error but I remove it, render `404`
- [x] Handle the scenario correctly where the user-created `error.js` has an error (fallback + `console.error` in main terminal is acceptable for this)
- [x] Hot code reloading of `error.js` works when rendering an error
