### ISSUE TITLE
2.0 checklist

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#409]
- [x] `next.config.js`
- [x] Upgrade to Webpack 2.0 #287
- [x] Switch to more optimized main bundle / ditch CDN
- [x] Document singleton `Router` API
- [x] Document programmatic server API in README
- [x] Add `config.babel` `Object` + `Function` support
  - [x] Document adding an additional babel transformation in README (`do-expressions`)
- [x] Make sure we flush `head` and CSS upon errors #439
- [x] Add missing `README`s in `examples/` and link to them throughout the README
- [x] Document usage of SSR styling solutions with `<Document>` in `examples/`
  - [x] glamor
  - [x] styled-components
  - [x] styletron
- [x] Incorporate `styled-jsx` and update
  - [x] Readme
  - [ ] Blog post 
  - [x] Examples
- [x] Show dev-mode deprecation for `pushTo` and `replaceTo`
- [x] Show dev-mode deprecation notice for `next/css` and point to the glamor example
- [ ] Router events

**Comment by lukeed** [comment]
IMO, for a `2.0` release, `glamor` should be removed entirely (as a breaking change) instead of showing a dev-only [deprecation message](https://github.com/zeit/next.js/blob/master/lib/css.js#L4). This still includes it within the bundle. 

This route would have made sense is `1.3` was the next target release.

Happy to tackle this if it's wanted.

**Comment by rauchg** [comment]
@lukeed I want to give people some time to migrate away. We can do a `3.0` release soon that removes it.

**Comment by frol** [comment]
3.0 release is coming, so this issue can be closed, I suppose :)

**Comment by arunoda** [comment]
Yes it is :)
